parameters:
  ros_metapackage: 'ros-melodic-desktop'
  pre_build: []

jobs:
- job: Build
  pool:
    vmImage: 'vs2017-win2016'
  timeoutInMinutes: 240
  steps:
  - script: |
      c: & cd c:\
      cmdkey /generic:LegacyGeneric:target=git:https://seanyen2018@dev.azure.com/seanyen2018/default/_git/rosdeps_cache /user:"Agent PAT" /password:"%SYSTEM_ACCESSTOKEN%"
      git clone https://seanyen2018@dev.azure.com/seanyen2018/default/_git/rosdeps_cache -b build/20181113.16
    env:
      SYSTEM_ACCESSTOKEN: $(System.AccessToken)
  - script: |
      mklink /d c:\opt c:\rosdeps_cache
      choco sources add -n=roswin -s https://roswin.azurewebsites.net/api/v2/ --priority 1
  - ${{ parameters.pre_build }}
  - script: |
      call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
      call "C:\opt\ros\melodic\x64\env.bat" catkin_init_workspace
      call "C:\opt\ros\melodic\x64\env.bat" catkin_make_isolated --install --source .
